const translations = {
    en: {
        title: "TPA Group FZE - Heavy Machinery Parts",
        header_title: "TPA Group FZE",
        home: "Home",
        about: "About",
        products: "Products",
        advantages: "Advantages",
        contacts: "Contacts",
        home_text: "We have long-term business relationships with leading global manufacturers.",
        about_title: "About Us",
        about_text: "\"SpetsMarket\" is a company that has been operating for over 10 years in the field of supplying equipment and spare parts for heavy machinery. We successfully cooperate with major Russian factories and constantly update the range for you.",
        about_brands: "17",
        about_brands_text: "Partner Brands",
        about_experience: "10",
        about_experience_text: "Years of Experience",
        about_cities: "400",
        about_cities_text: "Cities of Delivery",
        products_title: "Our Product Range",
        products_parts: "Spare Parts",
        products_parts_text: "High-quality spare parts for all types of heavy machinery.",
        products_components: "Components",
        products_components_text: "Pumps, distributors, reducers, and other essential components.",
        products_services: "Repair Services",
        products_services_text: "Professional repair and maintenance services for machinery.",
        advantages_title: "Our Advantages",
        advantages_import: "Import Substitution",
        advantages_import_text: "Experience in import substitution, ensuring reliable local sourcing.",
        advantages_quality: "Quality Control",
        advantages_quality_text: "We have our own quality control department to ensure product standards.",
        advantages_support: "24/7 Support",
        advantages_support_text: "Support and service available around the clock.",
        footer_contact: "Contact Us:",
        footer_phone: "Phone: <a href=\"tel:+9715829957076\">+9715829957076</a>",
        footer_address: "<b>Address:</b> UAE, Dubai, Business Bay, The Binary Tower, 32 Marasi Drive Street, 21st floor, Office 1",
        footer_email: "<b>Email:</b> slvtpa083@gmail.com"
    },
    fr: {
        title: "TPA Group FZE - Pièces de Machinerie Lourde",
        header_title: "TPA Group FZE",
        home: "Accueil",
        about: "À Propos",
        products: "Produits",
        advantages: "Avantages",
        contacts: "Contacts",
        home_text: "Nous avons des relations commerciales de longue date avec des fabricants mondiaux de premier plan.",
        about_title: "À Propos de Nous",
        about_text: "\"SpetsMarket\" est une entreprise qui opère depuis plus de 10 ans dans le domaine de la fourniture d'équipements et de pièces de rechange pour machines lourdes. Nous coopérons avec les principaux fabricants russes et mettons constamment à jour l'offre pour vous.",
        about_brands: "17",
        about_brands_text: "Marques Partenaires",
        about_experience: "10",
        about_experience_text: "Années d'Expérience",
        about_cities: "400",
        about_cities_text: "Villes de Livraison",
        products_title: "Notre Gamme de Produits",
        products_parts: "Pièces de Rechange",
        products_parts_text: "Pièces de rechange de haute qualité pour tous les types de machines lourdes.",
        products_components: "Composants",
        products_components_text: "Pompes, répartiteurs, réducteurs et autres composants essentiels.",
        products_services: "Services de Réparation",
        products_services_text: "Services de réparation et d'entretien professionnels pour les machines.",
        advantages_title: "Nos Avantages",
        advantages_import: "Substitution des Importations",
        advantages_import_text: "Expérience en substitution des importations, garantissant une source locale fiable.",
        advantages_quality: "Contrôle de Qualité",
        advantages_quality_text: "Nous avons notre propre département de contrôle qualité pour assurer les normes des produits.",
        advantages_support: "Support 24/7",
        advantages_support_text: "Support et service disponibles en permanence.",
        footer_contact: "Contactez-Nous:",
        footer_phone: "Téléphone: <a href=\"tel:+9715829957076\">+9715829957076</a>",
        footer_address: "<b>Adresse:</b> Émirats Arabes Unis, Dubaï, Business Bay, The Binary Tower, 32 Marasi Drive Street, 21e étage, Bureau 1",
        footer_email: "<b>Email:</b> slvtpa083@gmail.com"
    },
    de: {
        title: "TPA Group FZE - Ersatzteile für schwere Maschinen",
        header_title: "TPA Group FZE",
        home: "Startseite",
        about: "Über uns",
        products: "Produkte",
        advantages: "Vorteile",
        contacts: "Kontakte",
        home_text: "Wir pflegen langfristige Geschäftsbeziehungen zu führenden globalen Herstellern.",
        about_title: "Über uns",
        about_text: "\"SpetsMarket\" ist ein Unternehmen, das seit über 10 Jahren im Bereich der Lieferung von Ausrüstung und Ersatzteilen für schwere Maschinen tätig ist. Wir arbeiten erfolgreich mit großen russischen Fabriken zusammen und aktualisieren ständig unser Sortiment für Sie.",
        about_brands: "17",
        about_brands_text: "Partner-Marken",
        about_experience: "10",
        about_experience_text: "Jahre Erfahrung",
        about_cities: "400",
        about_cities_text: "Lieferstädte",
        products_title: "Unser Produktsortiment",
        products_parts: "Ersatzteile",
        products_parts_text: "Hochwertige Ersatzteile für alle Arten von schweren Maschinen.",
        products_components: "Komponenten",
        products_components_text: "Pumpen, Verteiler, Reduzierer und andere wichtige Komponenten.",
        products_services: "Reparaturdienste",
        products_services_text: "Professionelle Reparatur- und Wartungsdienste für Maschinen.",
        advantages_title: "Unsere Vorteile",
        advantages_import: "Importsubstitution",
        advantages_import_text: "Erfahrung in der Importsubstitution, die zuverlässige lokale Beschaffung gewährleistet.",
        advantages_quality: "Qualitätskontrolle",
        advantages_quality_text: "Wir haben unsere eigene Qualitätskontrollabteilung, um die Produktstandards sicherzustellen.",
        advantages_support: "24/7 Unterstützung",
        advantages_support_text: "Support und Service rund um die Uhr verfügbar.",
        footer_contact: "Kontaktieren Sie uns:",
        footer_phone: "Telefon: <a href=\"tel:+9715829957076\">+9715829957076</a>",
        footer_address: "<b>Adresse:</b> VAE, Dubai, Business Bay, The Binary Tower, 32 Marasi Drive Street, 21. Etage, Büro 1",
        footer_email: "<b>Email:</b> slvtpa083@gmail.com"
    },
    ru: {
        title: "TPA Group FZE - Запчасти для тяжелой техники",
        header_title: "TPA Group FZE",
        home: "Главная",
        about: "О нас",
        products: "Продукты",
        advantages: "Преимущества",
        contacts: "Контакты",
        home_text: "У нас долгосрочные деловые отношения с ведущими мировыми производителями.",
        about_title: "О компании",
        about_text: "\"SpetsMarket\" — это компания, работающая более 10 лет в области поставок оборудования и запасных частей для тяжелой техники. Мы успешно сотрудничаем с крупными российскими заводами и постоянно обновляем ассортимент для вас.",
        about_brands: "17",
        about_brands_text: "Партнерские бренды",
        about_experience: "10",
        about_experience_text: "Лет опыта",
        about_cities: "400",
        about_cities_text: "Города доставки",
        products_title: "Наш ассортимент продукции",
        products_parts: "Запчасти",
        products_parts_text: "Запчасти высокого качества для всех типов тяжелой техники.",
        products_components: "Компоненты",
        products_components_text: "Насосы, распределители, редукторы и другие важные компоненты.",
        products_services: "Ремонтные услуги",
        products_services_text: "Профессиональные услуги по ремонту и техническому обслуживанию техники.",
        advantages_title: "Наши преимущества",
        advantages_import: "Импортозамещение",
        advantages_import_text: "Опыт в импортозамещении, гарантируя надежное локальное снабжение.",
        advantages_quality: "Контроль качества",
        advantages_quality_text: "У нас есть собственный отдел контроля качества для обеспечения стандартов продукции.",
        advantages_support: "Круглосуточная поддержка",
        advantages_support_text: "Поддержка и обслуживание доступны круглосуточно.",
        footer_contact: "Свяжитесь с нами:",
        footer_phone: "Телефон: <a href=\"tel:+9715829957076\">+9715829957076</a>",
        footer_address: "<b>Адрес:</b> ОАЭ, Дубай, Business Bay, The Binary Tower, 32 Marasi Drive Street, 21-й этаж, Офис 1",
        footer_email: "<b>Email:</b> slvtpa083@gmail.com"
    },
    ar: {
        title: "TPA Group FZE - قطع غيار الآلات الثقيلة",
        header_title: "TPA Group FZE",
        home: "الرئيسية",
        about: "معلومات عنا",
        products: "المنتجات",
        advantages: "المزايا",
        contacts: "اتصل بنا",
        home_text: "لدينا علاقات تجارية طويلة الأمد مع كبار الشركات المصنعة العالمية.",
        about_title: "معلومات عنا",
        about_text: "\"SpetsMarket\" هي شركة تعمل منذ أكثر من 10 سنوات في مجال توريد المعدات وقطع الغيار للآلات الثقيلة. نحن نتعاون بنجاح مع مصانع روسية كبرى ونعمل على تحديث تشكيلة المنتجات لدينا من أجلك.",
        about_brands: "17",
        about_brands_text: "العلامات التجارية الشريكة",
        about_experience: "10",
        about_experience_text: "سنوات من الخبرة",
        about_cities: "400",
        about_cities_text: "مدن التوصيل",
        products_title: "مجموعة منتجاتنا",
        products_parts: "قطع غيار",
        products_parts_text: "قطع غيار عالية الجودة لجميع أنواع الآلات الثقيلة.",
        products_components: "مكونات",
        products_components_text: "المضخات، الموزعات، المخفضات، والمكونات الأساسية الأخرى.",
        products_services: "خدمات الإصلاح",
        products_services_text: "خدمات إصلاح وصيانة مهنية للآلات.",
        advantages_title: "مزايا",
        advantages_import: "استبدال الواردات",
        advantages_import_text: "خبرة في استبدال الواردات، مما يضمن الحصول على مصدر محلي موثوق.",
        advantages_quality: "رقابة الجودة",
        advantages_quality_text: "لدينا قسم خاص لمراقبة الجودة لضمان معايير المنتجات.",
        advantages_support: "دعم 24/7",
        advantages_support_text: "الدعم والخدمات متاحة على مدار الساعة.",
        footer_contact: "اتصل بنا:",
        footer_phone: "الهاتف: <a href=\"tel:+9715829957076\">+9715829957076</a>",
        footer_address: "<b>العنوان:</b> الإمارات العربية المتحدة، دبي، Business Bay، The Binary Tower، 32 Marasi Drive Street، الطابق 21، مكتب 1",
        footer_email: "<b>البريد الإلكتروني:</b> slvtpa083@gmail.com"
    }
};

document.addEventListener('DOMContentLoaded', () => {
    const languageSelect = document.getElementById('language-select');
    
    // Set default language
    updateTextContent('en');

    languageSelect.addEventListener('change', (event) => {
        const selectedLang = event.target.value;
        updateTextContent(selectedLang);
    });

    function updateTextContent(lang) {
        const elements = document.querySelectorAll('[data-lang]');
        elements.forEach(element => {
            const key = element.getAttribute('data-lang');
            if (translations[lang] && translations[lang][key]) {
                if (element.tagName === 'TITLE') {
                    document.title = translations[lang][key];
                } else {
                    element.innerHTML = translations[lang][key];
                }
            }
        });
    }
});
